--- 
abstract: Integrat FormFu and LDAP
author: Andreas Marienborg <andreas@startsiden.no>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-FormFu-Model-LDAP
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::FormFu: 0.02000
  Net::LDAP: 0
version: 0.0100
